CREATE TABLE IF NOT EXISTS appjobs ();

ALTER TABLE appjobs
  ADD COLUMN id SERIAL PRIMARY KEY,
  ADD COLUMN service VARCHAR(20) NOT NULL,
  ADD COLUMN route VARCHAR(20) NOT NULL,
  ADD COLUMN job_id UUID NOT NULL,
  ADD CONSTRAINT fk_appjobs_escalonjobs FOREIGN KEY (job_id) REFERENCES escalonjobs (id) ON DELETE CASCADE;
