
# {{{ health checkers
### profiles - users - auth
GET http://localhost:8001/health

GET http://localhost:8002/health

GET http://localhost:8003/health

### fmc
GET http://localhost:8005/health

### questions - answers
GET http://localhost:8011/health

GET http://localhost:8012/health

### modules
GET http://localhost:8021/health

### resources - papers
GET http://localhost:8031/health

GET http://localhost:8032/health

### local
GET http://localhost:8000/health
# }}}

### auth bypass
GET http://localhost:8003/auth/bypass/1
Accept: application/json

# {{{ example

GET http://localhost:8002/cron/
Accept: application/json
Content-type: application/json

GET http://localhost:8002/cron/1
Accept: application/json
Content-type: application/json

POST http://localhost:8001/cron/
Accept: application/json
Content-type: application/json

{
  "service": "servicio",
  "route": "ruta--",
  "job": {
    "schedule": "0/2 * * * * *"
  }
}

# }}}

#     "schedule": "0/2 * * * * *",
#     "since": "2023-09-21T12:10:00.0+0200",
#     "until": "2023-09-21T12:10:30.0+0200"
